version: '3'
services:
  web:
    image: chinmayapradhan/my-webapp:2.0
    ports:
      - 8090:8080
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-pwd
    volumes:
      - db-data:/var/lib/mysql
    restart: always
volumes:
   db-data: 