--- 
plugin: amazon.aws.aws_ec2

regions:
- us-east-2

#filters:
  #tag:Name: dev*
  #instance-state-name: running

keyed_groups:
 - key: tags
   prefix: tag
 - key: instance_type
   prefix: instance_type